apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: siva
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: almalinux
    image: almalinux:latest
    command: ["sleep", "900000000000"]
    