apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  namespace: siva
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: tomcat
    image: tomcat:9.0
    ports:
    - containerPort: 8080