apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # every k8s service have some labels
    app: myapp
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these labels should match with pod labels
      tier: frontend
      env: dev
  template: # this is pod definition
    metadata:
      labels: # these are pod labels
        tier: frontend
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
