apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc # assigning name to the container port

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    env: dev
    app: frontend
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 80 # this port belongs to service 
    targetPort: http-web-svc # here we can mention container port number or name.

